"""Portable complete C03 literal catalog; no dispatch or acceptance authority.

Definitions are prospectively authored from frozen V0/M1 prose and the explicit
norm resolutions. No candidate code, retained run, observation or response is
consulted to construct these values. Slash-bearing retained row IDs deliberately
cannot be submitted to the older CasePlan/SuitePlan schema without a new bridge.
"""
from __future__ import annotations

from collections import Counter
from functools import lru_cache
import hashlib
from types import MappingProxyType
from typing import Any

from . import candidate_http_cases_actions_v1 as actions
from . import candidate_http_cases_documents_v1 as documents
from . import candidate_http_cases_intake_v1 as intake
from . import candidate_http_cases_paths_v1 as paths
from . import candidate_http_cases_persistence_v1 as persistence
from . import candidate_http_cases_shapes_v1 as shapes
from .candidate_http_cases_core_v1 import LiteralCase, PROTOCOL, encode, require

RETAINED_ROSTER_SHA256 = "2c716eea838784446f73f5d1434d4308f80cbd070ff5d9c04976ba287abfc32e"
BASE_COMMIT = "09200a25218a31ce01add5e872bfb6e677b8d662"
# These are immutable provenance pins, not a runtime registration or verification.
NORMATIVE_AND_VALUE_SOURCE_PINS = (('gossip_harness/library_project_fixture_v1.py', 'fa4440f1ac7e63e3b4ef7d9978a8970e8d6cd688efe9c2e1b6d1e75c0f757caf'), ('analysis/candidate-b03-c03-policy-review-v1.json', 'bec2139ba2b6e99d5ac6da01296842cc690af5c84f3428aaa5183eaf2ec54570'), ('analysis/candidate-c03-http-catalog-norms-v1.json', '24a9c469ec994c3e17bcfb0da7e89f171ac55022e6415a5bcc1d61d6817d71a4'), ('docs/candidate-c03-http-catalog-norms-v1.md', 'd075a3adc03fae8f7ee14631643fead57144be69c1f5072b79574c04ef3dfbc6'), ('gossip_harness/candidate_http_fixtures_v1.py', 'ddcb37083efdfaee47b857438d592bfad4bfdff433dbcbad343512feb115c257'), ('gossip_harness/candidate_http_semantics_v1.py', 'ce59b1a1cfb2cfb2b39632486c90a0023789ab72b51c13987c654a57f240958f'), ('gossip_harness/candidate_http_transport_v1.py', 'a283e205ac3228085da1cf19c1ac60c720f13a0841463134605f0eb984f98ddd'))

FAMILY_COUNTS = MappingProxyType({'HTTP-EMPTY-HEALTH': 6, 'HTTP-DOCUMENT-ROUTES': 26, 'HTTP-ERROR-STATUS': 11, 'HTTP-POST-SHAPES': 56, 'HTTP-QUERY-VALUES': 8, 'HTTP-BODY-WIRE': 9, 'HTTP-INTAKE-ROUTES': 27, 'HTTP-ACTION-STATE': 58, 'HTTP-ROOT-PATH': 69, 'HTTP-PERSIST-LISTENER': 6})
FAMILY_TARGETS = MappingProxyType({'HTTP-EMPTY-HEALTH': ('V0-HTTP-01', 'V0-HTTP-02', 'V0-HTTP-04', 'M1-HTTP-01', 'M1-HTTP-02'), 'HTTP-DOCUMENT-ROUTES': ('V0-HTTP-01', 'V0-HTTP-02'), 'HTTP-ERROR-STATUS': ('V0-HTTP-02', 'M1-HTTP-02'), 'HTTP-POST-SHAPES': ('V0-HTTP-02', 'M1-HTTP-01', 'M1-I30'), 'HTTP-QUERY-VALUES': ('V0-HTTP-01', 'V0-HTTP-02'), 'HTTP-BODY-WIRE': ('V0-HTTP-03',), 'HTTP-INTAKE-ROUTES': ('M1-HTTP-01', 'M1-HTTP-02', 'M1-I30', 'M1-I31'), 'HTTP-ACTION-STATE': ('M1-HTTP-01', 'M1-HTTP-02'), 'HTTP-ROOT-PATH': ('M1-I31',), 'HTTP-PERSIST-LISTENER': ('V0-HTTP-01', 'M1-HTTP-01')})
TARGET_IDS = ('V0-HTTP-01', 'V0-HTTP-02', 'V0-HTTP-03', 'V0-HTTP-04', 'M1-HTTP-01', 'M1-HTTP-02', 'M1-I30', 'M1-I31')

ROW_IDS = (
    'HTTP-EMPTY-HEALTH/documents',
    'HTTP-EMPTY-HEALTH/export',
    'HTTP-EMPTY-HEALTH/jobs',
    'HTTP-EMPTY-HEALTH/health',
    'HTTP-EMPTY-HEALTH/missing-documents',
    'HTTP-EMPTY-HEALTH/missing-jobs',
    'HTTP-DOCUMENT-ROUTES/import-0',
    'HTTP-DOCUMENT-ROUTES/import-1',
    'HTTP-DOCUMENT-ROUTES/import-2',
    'HTTP-DOCUMENT-ROUTES/import-3',
    'HTTP-DOCUMENT-ROUTES/unchanged-import',
    'HTTP-DOCUMENT-ROUTES/all',
    'HTTP-DOCUMENT-ROUTES/none',
    'HTTP-DOCUMENT-ROUTES/one',
    'HTTP-DOCUMENT-ROUTES/casefold',
    'HTTP-DOCUMENT-ROUTES/literal',
    'HTTP-DOCUMENT-ROUTES/unicode-casefold',
    'HTTP-DOCUMENT-ROUTES/offset-one',
    'HTTP-DOCUMENT-ROUTES/limit-one',
    'HTTP-DOCUMENT-ROUTES/offset-beyond',
    'HTTP-DOCUMENT-ROUTES/offset-positive-limit',
    'HTTP-DOCUMENT-ROUTES/query-256',
    'HTTP-DOCUMENT-ROUTES/show-0',
    'HTTP-DOCUMENT-ROUTES/show-1',
    'HTTP-DOCUMENT-ROUTES/show-2',
    'HTTP-DOCUMENT-ROUTES/show-3',
    'HTTP-DOCUMENT-ROUTES/export-all',
    'HTTP-DOCUMENT-ROUTES/export-empty',
    'HTTP-DOCUMENT-ROUTES/export-reverse',
    'HTTP-DOCUMENT-ROUTES/export-one',
    'HTTP-DOCUMENT-ROUTES/export-duplicate',
    'HTTP-DOCUMENT-ROUTES/export-missing-after-valid',
    'HTTP-ERROR-STATUS/missing-document',
    'HTTP-ERROR-STATUS/missing-job',
    'HTTP-ERROR-STATUS/source-changed',
    'HTTP-ERROR-STATUS/job-conflict',
    'HTTP-ERROR-STATUS/job-state',
    'HTTP-ERROR-STATUS/stale-epoch',
    'HTTP-ERROR-STATUS/invalid-request',
    'HTTP-ERROR-STATUS/unknown-route',
    'HTTP-ERROR-STATUS/io-error-directory',
    'HTTP-ERROR-STATUS/io-error-zip',
    'HTTP-ERROR-STATUS/io-error-json',
    'HTTP-POST-SHAPES/import-missing-source',
    'HTTP-POST-SHAPES/import-extra',
    'HTTP-POST-SHAPES/export-missing-ids',
    'HTTP-POST-SHAPES/export-extra',
    'HTTP-POST-SHAPES/submit-entries-missing-job_id',
    'HTTP-POST-SHAPES/submit-entries-missing-entries',
    'HTTP-POST-SHAPES/submit-entries-extra',
    'HTTP-POST-SHAPES/submit-directory-missing-job_id',
    'HTTP-POST-SHAPES/submit-directory-missing-directory',
    'HTTP-POST-SHAPES/submit-directory-missing-namespace',
    'HTTP-POST-SHAPES/submit-directory-extra',
    'HTTP-POST-SHAPES/submit-zip-missing-job_id',
    'HTTP-POST-SHAPES/submit-zip-missing-zip',
    'HTTP-POST-SHAPES/submit-zip-missing-namespace',
    'HTTP-POST-SHAPES/submit-zip-extra',
    'HTTP-POST-SHAPES/submit-json-missing-job_id',
    'HTTP-POST-SHAPES/submit-json-missing-json',
    'HTTP-POST-SHAPES/submit-json-extra',
    'HTTP-POST-SHAPES/prepare-extra',
    'HTTP-POST-SHAPES/commit-missing-epoch',
    'HTTP-POST-SHAPES/commit-extra',
    'HTTP-POST-SHAPES/cancel-extra',
    'HTTP-POST-SHAPES/retry-extra',
    'HTTP-POST-SHAPES/multiple-entries-directory',
    'HTTP-POST-SHAPES/multiple-entries-zip',
    'HTTP-POST-SHAPES/multiple-entries-json',
    'HTTP-POST-SHAPES/multiple-directory-zip',
    'HTTP-POST-SHAPES/multiple-directory-json',
    'HTTP-POST-SHAPES/multiple-zip-json',
    'HTTP-POST-SHAPES/no-selector',
    'HTTP-POST-SHAPES/json-namespace',
    'HTTP-POST-SHAPES/job-id-empty',
    'HTTP-POST-SHAPES/job-id-65-ascii',
    'HTTP-POST-SHAPES/job-id-non-ascii',
    'HTTP-POST-SHAPES/job-id-space',
    'HTTP-POST-SHAPES/job-id-slash',
    'HTTP-POST-SHAPES/job-id-boolean',
    'HTTP-POST-SHAPES/job-id-null',
    'HTTP-POST-SHAPES/job-id-number',
    'HTTP-POST-SHAPES/job-id-valid-one',
    'HTTP-POST-SHAPES/job-id-valid-64-ascii',
    'HTTP-POST-SHAPES/job-id-valid-punctuation',
    'HTTP-POST-SHAPES/entries-shape-object',
    'HTTP-POST-SHAPES/entries-shape-null',
    'HTTP-POST-SHAPES/entries-shape-string',
    'HTTP-POST-SHAPES/entries-shape-number',
    'HTTP-POST-SHAPES/entries-shape-entry-nonobject',
    'HTTP-POST-SHAPES/entries-shape-entry-missing-text',
    'HTTP-POST-SHAPES/directory-path-type-null',
    'HTTP-POST-SHAPES/directory-path-type-number',
    'HTTP-POST-SHAPES/zip-path-type-null',
    'HTTP-POST-SHAPES/zip-path-type-number',
    'HTTP-POST-SHAPES/json-path-type-null',
    'HTTP-POST-SHAPES/json-path-type-number',
    'HTTP-POST-SHAPES/offline-hook-false',
    'HTTP-POST-SHAPES/offline-hook-true',
    'HTTP-QUERY-VALUES/0-offset',
    'HTTP-QUERY-VALUES/1-limit',
    'HTTP-QUERY-VALUES/2-offset',
    'HTTP-QUERY-VALUES/3-limit',
    'HTTP-QUERY-VALUES/4-limit',
    'HTTP-QUERY-VALUES/5-q',
    'HTTP-QUERY-VALUES/6-offset',
    'HTTP-QUERY-VALUES/7-limit',
    'HTTP-BODY-WIRE/raw-bytes-65536',
    'HTTP-BODY-WIRE/raw-bytes-65537',
    'HTTP-BODY-WIRE/wrong-media',
    'HTTP-BODY-WIRE/missing-media',
    'HTTP-BODY-WIRE/malformed-json',
    'HTTP-BODY-WIRE/array',
    'HTTP-BODY-WIRE/string',
    'HTTP-BODY-WIRE/null',
    'HTTP-BODY-WIRE/number',
    'HTTP-INTAKE-ROUTES/entries-nonempty',
    'HTTP-INTAKE-ROUTES/entries-empty',
    'HTTP-INTAKE-ROUTES/directory-nonempty',
    'HTTP-INTAKE-ROUTES/directory-empty',
    'HTTP-INTAKE-ROUTES/zip-nonempty',
    'HTTP-INTAKE-ROUTES/zip-empty',
    'HTTP-INTAKE-ROUTES/json-nonempty',
    'HTTP-INTAKE-ROUTES/json-empty',
    'HTTP-INTAKE-ROUTES/lexical-jobs-order',
    'HTTP-INTAKE-ROUTES/zip-syntax',
    'HTTP-INTAKE-ROUTES/json-syntax',
    'HTTP-INTAKE-ROUTES/json-schema',
    'HTTP-INTAKE-ROUTES/zip-bad-utf8',
    'HTTP-INTAKE-ROUTES/directory-bad-utf8',
    'HTTP-INTAKE-ROUTES/zip-duplicate-key',
    'HTTP-INTAKE-ROUTES/zip-symlink-member',
    'HTTP-INTAKE-ROUTES/zip-nonregular-member',
    'HTTP-INTAKE-ROUTES/entries-semantic-deferred-traversal',
    'HTTP-INTAKE-ROUTES/entries-semantic-deferred-unsupported',
    'HTTP-INTAKE-ROUTES/json-semantic-deferred-traversal',
    'HTTP-INTAKE-ROUTES/json-semantic-deferred-unsupported',
    'HTTP-INTAKE-ROUTES/directory-file-count-64',
    'HTTP-INTAKE-ROUTES/directory-file-count-65',
    'HTTP-INTAKE-ROUTES/zip-file-count-64',
    'HTTP-INTAKE-ROUTES/zip-file-count-65',
    'HTTP-INTAKE-ROUTES/json-file-count-64',
    'HTTP-INTAKE-ROUTES/json-file-count-65',
    'HTTP-ACTION-STATE/queued-prepare',
    'HTTP-ACTION-STATE/queued-commit',
    'HTTP-ACTION-STATE/queued-cancel',
    'HTTP-ACTION-STATE/queued-retry',
    'HTTP-ACTION-STATE/queued-stale-commit',
    'HTTP-ACTION-STATE/queued-submit-same-canonical-manifest-reversed',
    'HTTP-ACTION-STATE/queued-submit-different-manifest',
    'HTTP-ACTION-STATE/queued-reopen',
    'HTTP-ACTION-STATE/running-prepare',
    'HTTP-ACTION-STATE/running-commit',
    'HTTP-ACTION-STATE/running-cancel',
    'HTTP-ACTION-STATE/running-retry',
    'HTTP-ACTION-STATE/running-stale-commit',
    'HTTP-ACTION-STATE/running-submit-same-canonical-manifest-reversed',
    'HTTP-ACTION-STATE/running-submit-different-manifest',
    'HTTP-ACTION-STATE/running-reopen',
    'HTTP-ACTION-STATE/completed-prepare',
    'HTTP-ACTION-STATE/completed-commit',
    'HTTP-ACTION-STATE/completed-cancel',
    'HTTP-ACTION-STATE/completed-retry',
    'HTTP-ACTION-STATE/completed-stale-commit',
    'HTTP-ACTION-STATE/completed-submit-same-canonical-manifest-reversed',
    'HTTP-ACTION-STATE/completed-submit-different-manifest',
    'HTTP-ACTION-STATE/completed-reopen',
    'HTTP-ACTION-STATE/cancelled-prepare',
    'HTTP-ACTION-STATE/cancelled-commit',
    'HTTP-ACTION-STATE/cancelled-cancel',
    'HTTP-ACTION-STATE/cancelled-retry',
    'HTTP-ACTION-STATE/cancelled-stale-commit',
    'HTTP-ACTION-STATE/cancelled-submit-same-canonical-manifest-reversed',
    'HTTP-ACTION-STATE/cancelled-submit-different-manifest',
    'HTTP-ACTION-STATE/cancelled-reopen',
    'HTTP-ACTION-STATE/failed-prepare',
    'HTTP-ACTION-STATE/failed-commit',
    'HTTP-ACTION-STATE/failed-cancel',
    'HTTP-ACTION-STATE/failed-retry',
    'HTTP-ACTION-STATE/failed-stale-commit',
    'HTTP-ACTION-STATE/failed-submit-same-canonical-manifest-reversed',
    'HTTP-ACTION-STATE/failed-submit-different-manifest',
    'HTTP-ACTION-STATE/failed-reopen',
    'HTTP-ACTION-STATE/missing-prepare',
    'HTTP-ACTION-STATE/missing-commit',
    'HTTP-ACTION-STATE/missing-cancel',
    'HTTP-ACTION-STATE/missing-retry',
    'HTTP-ACTION-STATE/old-token-after-cancelled',
    'HTTP-ACTION-STATE/old-token-after-retried-queued',
    'HTTP-ACTION-STATE/old-token-after-reprepared-running',
    'HTTP-ACTION-STATE/old-token-after-successor-completed',
    'HTTP-ACTION-STATE/queued-invalid-prepare',
    'HTTP-ACTION-STATE/running-prepare-after-import',
    'HTTP-ACTION-STATE/commit-rechecks-direct-import',
    'HTTP-ACTION-STATE/failed-retry-prepare-fails-again',
    'HTTP-ACTION-STATE/old-token-after-successor-failed',
    'HTTP-ACTION-STATE/queued-get-single-job',
    'HTTP-ACTION-STATE/running-get-single-job',
    'HTTP-ACTION-STATE/completed-get-single-job',
    'HTTP-ACTION-STATE/cancelled-get-single-job',
    'HTTP-ACTION-STATE/failed-get-single-job',
    'HTTP-ROOT-PATH/directory-nested',
    'HTTP-ROOT-PATH/directory-absolute',
    'HTTP-ROOT-PATH/directory-traversal',
    'HTTP-ROOT-PATH/directory-direct-link',
    'HTTP-ROOT-PATH/directory-ancestor-link',
    'HTTP-ROOT-PATH/directory-wrong-kind',
    'HTTP-ROOT-PATH/directory-lexical-backslash',
    'HTTP-ROOT-PATH/directory-lexical-empty-segment',
    'HTTP-ROOT-PATH/directory-lexical-dot',
    'HTTP-ROOT-PATH/directory-lexical-nul',
    'HTTP-ROOT-PATH/directory-lexical-empty',
    'HTTP-ROOT-PATH/zip-nested',
    'HTTP-ROOT-PATH/zip-absolute',
    'HTTP-ROOT-PATH/zip-traversal',
    'HTTP-ROOT-PATH/zip-direct-link',
    'HTTP-ROOT-PATH/zip-ancestor-link',
    'HTTP-ROOT-PATH/zip-wrong-kind',
    'HTTP-ROOT-PATH/zip-lexical-backslash',
    'HTTP-ROOT-PATH/zip-lexical-empty-segment',
    'HTTP-ROOT-PATH/zip-lexical-dot',
    'HTTP-ROOT-PATH/zip-lexical-nul',
    'HTTP-ROOT-PATH/zip-lexical-empty',
    'HTTP-ROOT-PATH/zip-wrong-suffix',
    'HTTP-ROOT-PATH/json-nested',
    'HTTP-ROOT-PATH/json-absolute',
    'HTTP-ROOT-PATH/json-traversal',
    'HTTP-ROOT-PATH/json-direct-link',
    'HTTP-ROOT-PATH/json-ancestor-link',
    'HTTP-ROOT-PATH/json-wrong-kind',
    'HTTP-ROOT-PATH/json-lexical-backslash',
    'HTTP-ROOT-PATH/json-lexical-empty-segment',
    'HTTP-ROOT-PATH/json-lexical-dot',
    'HTTP-ROOT-PATH/json-lexical-nul',
    'HTTP-ROOT-PATH/json-lexical-empty',
    'HTTP-ROOT-PATH/json-wrong-suffix',
    'HTTP-ROOT-PATH/directory-namespace-empty',
    'HTTP-ROOT-PATH/directory-namespace-absolute',
    'HTTP-ROOT-PATH/directory-namespace-backslash',
    'HTTP-ROOT-PATH/directory-namespace-nul',
    'HTTP-ROOT-PATH/directory-namespace-empty-segment',
    'HTTP-ROOT-PATH/directory-namespace-dot',
    'HTTP-ROOT-PATH/directory-namespace-parent',
    'HTTP-ROOT-PATH/directory-namespace-trailing',
    'HTTP-ROOT-PATH/directory-namespace-segment129',
    'HTTP-ROOT-PATH/directory-combined-bytes-256',
    'HTTP-ROOT-PATH/directory-combined-bytes-257',
    'HTTP-ROOT-PATH/directory-combined-segments-16',
    'HTTP-ROOT-PATH/directory-combined-segments-17',
    'HTTP-ROOT-PATH/zip-namespace-empty',
    'HTTP-ROOT-PATH/zip-namespace-absolute',
    'HTTP-ROOT-PATH/zip-namespace-backslash',
    'HTTP-ROOT-PATH/zip-namespace-nul',
    'HTTP-ROOT-PATH/zip-namespace-empty-segment',
    'HTTP-ROOT-PATH/zip-namespace-dot',
    'HTTP-ROOT-PATH/zip-namespace-parent',
    'HTTP-ROOT-PATH/zip-namespace-trailing',
    'HTTP-ROOT-PATH/zip-namespace-segment129',
    'HTTP-ROOT-PATH/zip-combined-bytes-256',
    'HTTP-ROOT-PATH/zip-combined-bytes-257',
    'HTTP-ROOT-PATH/zip-combined-segments-16',
    'HTTP-ROOT-PATH/zip-combined-segments-17',
    'HTTP-ROOT-PATH/entries-source-bytes256',
    'HTTP-ROOT-PATH/entries-source-bytes257',
    'HTTP-ROOT-PATH/entries-source-segments16',
    'HTTP-ROOT-PATH/entries-source-segments17',
    'HTTP-ROOT-PATH/json-source-bytes256',
    'HTTP-ROOT-PATH/json-source-bytes257',
    'HTTP-ROOT-PATH/json-source-segments16',
    'HTTP-ROOT-PATH/json-source-segments17',
    'HTTP-PERSIST-LISTENER/http-normal-restart-cancel-retry',
    'HTTP-PERSIST-LISTENER/http-cli-http-same-db',
    'HTTP-PERSIST-LISTENER/root-independence-source-ids',
    'HTTP-PERSIST-LISTENER/root-change-source-changed',
    'HTTP-PERSIST-LISTENER/listener-all-epochs',
    'HTTP-PERSIST-LISTENER/root-page-reachable',
)
ROW_IDS_SHA256 = "5f734fc893a8d9387d043c110efa90dcb3dfdfd520e10b7712fd42127b10d171"
INTERACTION_ROWS = MappingProxyType({
    "HTTP-POST-SHAPES/offline-hook-false": ("M1-A08",),
    "HTTP-POST-SHAPES/offline-hook-true": ("M1-A08",),
    "HTTP-PERSIST-LISTENER/http-cli-http-same-db": ("V0-CLI-03",),
    "HTTP-PERSIST-LISTENER/listener-all-epochs": ("V0-CLI-03",),
    "HTTP-PERSIST-LISTENER/root-page-reachable": ("V0-CLI-03",),
})
INTERACTION_SCOPE = MappingProxyType({
    "M1-A08": "HTTP transport nonexposure only; no offline atomicity acceptance",
    "V0-CLI-03": "CLI/browser interaction only; no CLI or browser acceptance",
})


@lru_cache(maxsize=1)
def definitions() -> tuple[LiteralCase, ...]:
    """Return every exact immutable history in the retained ten-family order."""
    authored = tuple(case for shard in (documents, shapes, intake, actions, paths, persistence)
                     for case in shard.definitions())
    lookup = {case.row_id: case for case in authored}
    require(len(authored) == len(lookup) == len(ROW_IDS) == 276 and set(lookup) == set(ROW_IDS),
            "Authored rows must exactly cover the complete frozen roster")
    ordered = tuple(lookup[row_id] for row_id in ROW_IDS)
    require(dict(Counter(case.family_id for case in ordered)) == dict(FAMILY_COUNTS),
            "Ten-family census differs")
    for case in ordered:
        require(case.requirement_ids == FAMILY_TARGETS[case.family_id], "Held target labels differ")
        require(case.interaction_ids == INTERACTION_ROWS.get(case.row_id, ()), "Separate interaction labels differ")
    require(set(target for case in ordered for target in case.requirement_ids) == set(TARGET_IDS),
            "Eight-target census differs")
    return ordered


def declared_counts() -> dict[str, Any]:
    """Exact allocation declarations; none of these counts describes execution."""
    cases = definitions()
    counts = tuple(case.counts for case in cases)
    return {"rows": len(cases), "families": len(FAMILY_COUNTS), "targets": len(TARGET_IDS),
            "totals": {key: sum(row[key] for row in counts) for key in counts[0]},
            "max_per_case": {key: max(row[key] for row in counts) for key in counts[0]},
            "cases_exceeding_v2_64_steps": [case.row_id for case in cases if case.counts["steps"] > 64],
            "max_request_body_bytes": max(len(step.request.body) for case in cases for step in case.steps if step.request),
            "max_request_wire_bytes": max(len(step.request.wire_bytes()) for case in cases for step in case.steps if step.request),
            "max_fixture_file_bytes": max(len(item.data) for case in cases for item in case.fixtures if item.kind == "file")}


def definition_manifest() -> dict[str, Any]:
    """Value identities only; source/runtime/purpose/evidence registration is open."""
    cases = definitions()
    return {"protocol": PROTOCOL, "base_commit": BASE_COMMIT,
            "retained_roster_sha256": RETAINED_ROSTER_SHA256,
            "row_ids_sha256": ROW_IDS_SHA256,
            "source_pins": [{"path": path, "sha256": digest} for path, digest in NORMATIVE_AND_VALUE_SOURCE_PINS],
            "case_definitions": [{"row_id": case.row_id, "sha256": case.definition_sha256} for case in cases],
            "counts": declared_counts(),
            "required_mechanics": sorted({value for case in cases for value in case.required_mechanics}),
            "dispatch_authority": False, "acceptance_authority": False, "fresh_execution": False,
            "product_verdict": "not_evaluated", "full_acceptance_denominator_unchanged": True,
            "prerequisites_open": [f"P{index:02d}" for index in range(1, 11)]}


def definition_sha256() -> str:
    return hashlib.sha256(encode(definition_manifest())).hexdigest()
