"""Trusted authored M4 composition and exact public binary fixture staging.

The authored application is not candidate input or comparative study evidence.
Binary compatibility snapshots are supplied by their independent fixture owner,
never serialized as arbitrary UTF-8 source or regenerated by this application.
"""
from __future__ import annotations

from pathlib import Path

from .library_cumulative_public_fixture_v1 import public_files
from .library_m3_reference_v1 import m3_files
from .library_m4_backup_reference_v1 import backup_files
from .library_m4_browser_reference_v1 import browser_files
from .library_m4_catalog_reference_v1 import catalog_files
from .library_m4_clients_reference_v1 import clients_files
from .library_m4_fixture_v1 import fixture_files, fixture_text_files
from .library_m4_release_reference_v1 import release_files

_STORE = """from library.catalog.m4_backup import M4BackupMixin
from library.catalog.maintenance import MaintenanceMixin
from library.catalog.worker import WorkerMixin
from library.catalog.m4_store import NormalizedStore


class Store(M4BackupMixin, MaintenanceMixin, WorkerMixin, NormalizedStore):
    pass
"""


def m4_files() -> dict[str, str]:
    """Return complete text sources; exact SQLite bytes have a separate API."""
    files = m3_files()
    owned: set[str] = set()
    for overlay in (catalog_files(), backup_files(), clients_files(), browser_files(),
                    public_files(), fixture_text_files(), {"library/catalog/store.py": _STORE}):
        if owned.intersection(overlay):
            raise ValueError("M4 reference overlay ownership collides")
        owned.update(overlay)
        files.update(overlay)
    release = release_files(sorted(set(files) | set(fixture_files())))
    if owned.intersection(release):
        raise ValueError("M4 release source ownership collides")
    files.update(release)
    return files


def m4_binary_files() -> dict[str, bytes]:
    """Return independently frozen binary snapshots outside source patches."""
    text = fixture_text_files()
    return {path: data for path, data in fixture_files().items() if path not in text}


def write_m4_project(path: Path) -> None:
    """Stage a fresh authored application with immutable public fixture bytes."""
    path = Path(path)
    path.mkdir(parents=True, exist_ok=False)
    sources = {name: source.encode("utf-8") for name, source in m4_files().items()}
    binaries = m4_binary_files()
    if set(sources).intersection(binaries):
        raise ValueError("M4 binary fixture shadows a text source")
    for name, data in sorted((sources | binaries).items()):
        relative = Path(name)
        if relative.is_absolute() or any(part in ("", ".", "..") for part in name.split("/")):
            raise ValueError("Unconfined authored source path")
        target = path / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("xb") as stream:
            stream.write(data)
