"""Authored prospective-v2 composition over immutable prior reference sources.

Explicit ownership transforms replace generated product files. The supported
schema3 predecessor uses the same v2 fencing/counter/ownership implementation,
not a rewritten historical M3 reference or a fabricated migration database.
"""
from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from .library_cumulative_public_fixture_v2 import public_files
from .library_m3_reference_v1 import m3_files
from .library_m4_reference_v1 import m4_binary_files, m4_files
from .library_v2_browser_reference_v1 import browser_files
from .library_v2_catalog_reference_v1 import catalog_files, schema3_catalog_files
from .library_v2_clients_reference_v1 import clients_files
from .library_v2_maintenance_reference_v1 import maintenance_files
from .library_v2_release_reference_v1 import release_files

_V2_STORE = '''from library.catalog.v2_maintenance import V2MaintenanceMixin
from library.catalog.m4_backup import M4BackupMixin
from library.catalog.maintenance import MaintenanceMixin
from library.catalog.worker import WorkerMixin
from library.catalog.m4_store import NormalizedStore


class Store(V2MaintenanceMixin, M4BackupMixin, MaintenanceMixin, WorkerMixin, NormalizedStore):
    pass
'''
_SCHEMA3_STORE = '''from library.catalog.v2_maintenance import V2MaintenanceMixin
from library.catalog.backup import BackupMixin
from library.catalog.maintenance import MaintenanceMixin
from library.catalog.worker import WorkerMixin
from library.catalog.control import CoreStore


class Store(V2MaintenanceMixin, BackupMixin, MaintenanceMixin, WorkerMixin, CoreStore):
    pass
'''


def _overlay(files: dict[str, str], changes: Mapping[str, str], owned: set[str]) -> None:
    """A base replacement is explicit; a second v2 owner of a path is an error."""
    collision = owned.intersection(changes)
    if collision:
        raise ValueError("V2 source ownership collides: " + ", ".join(sorted(collision)))
    owned.update(changes)
    files.update(changes)


def v2_files() -> dict[str, str]:
    files = m4_files()
    owned: set[str] = set()
    for transform in (catalog_files, maintenance_files, clients_files, browser_files):
        _overlay(files, transform(files), owned)
    _overlay(files, public_files(), owned)
    _overlay(files, {"library/catalog/store.py": _V2_STORE}, owned)
    _overlay(files, release_files(sorted(set(files) | set(v2_binary_files()))), owned)
    return files


def v2_binary_files() -> dict[str, bytes]:
    """Exact independent public v0/M2 snapshots, never regenerated by v2."""
    return m4_binary_files()


def schema3_v2_files() -> dict[str, str]:
    """Supported v2 schema3 predecessor for real retained-handle migrations."""
    files = m3_files()
    owned: set[str] = set()
    for transform in (schema3_catalog_files, maintenance_files):
        _overlay(files, transform(files), owned)
    _overlay(files, {"library/catalog/store.py": _SCHEMA3_STORE}, owned)
    return files


def _write(path: Path, files: Mapping[str, str], binaries: Mapping[str, bytes]) -> None:
    path = Path(path)
    if set(files).intersection(binaries):
        raise ValueError("V2 binary fixture shadows text")
    sources = {name: source.encode("utf-8") for name, source in files.items()} | dict(binaries)
    for name in sources:
        if (Path(name).is_absolute() or "\\" in name or "\0" in name
                or any(part in ("", ".", "..") for part in name.split("/"))):
            raise ValueError("Unconfined authored source path")
    path.mkdir(parents=True, exist_ok=False)
    for name, data in sorted(sources.items()):
        target = path / name
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("xb") as stream:
            stream.write(data)


def write_v2_project(path: Path) -> None:
    _write(path, v2_files(), v2_binary_files())


def write_schema3_v2_project(path: Path) -> None:
    _write(path, schema3_v2_files(), {})
